version: "3"

services:
  app:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput
             python manage.py migrate
             waitress-serve --port 8000 blob_vault.wsgi:application"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
