# Generated by Django 3.0.5 on 2020-04-19 10:57
# type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blob",
            fields=[
                ("content", models.BinaryField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("url", models.URLField()),
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
