# Generated by Django 3.0.5 on 2020-04-20 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_blob_mimetype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("creation_date", models.DateField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
    ]
