# Generated by Django 3.0.5 on 2020-04-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="creation_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
