# Generated by Django 3.0.5 on 2020-04-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_auto_20200420_1834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt", name="creation_date", field=models.DateTimeField(),
        ),
    ]
