# Generated by Django 3.0.5 on 2020-04-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_auto_20200420_2031"),
    ]

    operations = [
        migrations.RenameField(model_name="blob", old_name="uuid", new_name="id",),
        migrations.RenameField(model_name="receipt", old_name="uuid", new_name="id",),
    ]
