name: Django App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Lint with black
        run: |
          black --check app/
          black --check blob_vault/
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with mypy
        run: |
          mypy app/
          mypy blob_vault/
      - name: Check with Django check
        run: |
          python manage.py check
      - name: Test with Django test
        run: |
          python manage.py test
        env:
          EMAIL_QUOTA: 100
          EMAIL_SENDER: "blobvault@example.com"
          IS_DEBUG: "true"
          SECRET_KEY: "E.#{Kzy'aAA*eP'VZP'lUPRydPiHpWNY(ZLATFJX/$]Mxi*A-"
          SENDGRID_API_KEY: "|kwZj{.~{utC@Px~%&pvjBaG|D!A(/UQo]eV#AZN)dOXKe:S!m?]Q%Bc-@jAtj)KJii/E"
